**Numpy library**

In [3]:
print('hello')

hello


In [4]:
a = 2
a

2

In [8]:
a = 2
b = 3
print('a = '+str(a)+' and '+'b = '+str(b))

a = 2 and b = 3


In [10]:
type(a)

int

In [13]:
s1 = 'RJ college'
type(s1)

str

In [14]:
f=2.34546796547
type(f)

float

> indent


$y = x^2$

https://numpy.org/doc/stable/user/whatisnumpy.html

In [15]:
a=[1,2,3]
a

[1, 2, 3]

In [16]:
type(a)

list

In [17]:
b=[4,5,6]
b

[4, 5, 6]

In [20]:
c = []
for i in range(len(a)):
  c.append(a[i]*b[i])
c

[4, 10, 18]

In [21]:
c = []
for i in range(len(a)):
  c.append(a[i]+b[i])
c

[5, 7, 9]

In [22]:
import time
print('sleeping')
time.sleep(30)
print('done sleeping')

sleeping
done sleeping


In [26]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
a.ndim

2

In [28]:
a.dtype

dtype('int64')

In [29]:
a.dtype.name

'int64'

In [30]:
a.itemsize

8

In [32]:
a.size

15

In [33]:
type(a)

numpy.ndarray

In [39]:
b=np.array([[11,13,14],[56,57,58]])
b

array([[11, 13, 14],
       [56, 57, 58]])

In [40]:
b.reshape(3,2)
b

array([[11, 13, 14],
       [56, 57, 58]])

In [41]:
c=b.reshape(3,2)
c

array([[11, 13],
       [14, 56],
       [57, 58]])

In [45]:
d=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [46]:
e=d.reshape(2,5)
e

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')